### ISSUE TITLE
the navbar animation is different from the original

### ISSUE THREAD

**Issue by eoguvo** [wendell-kenneddy/brackets-uiclone#1]
possible solution

(remove div with class "x-line")
```css
#sections li {
  display: inline-block;
  position: relative;
  padding-bottom: 3px;
  margin-right: 10px;
}
#sections li:last-child {
  margin-right: 0;
}

#sections li:after {
  content: '';
  display: block;
  margin: auto;
  height: 3px;
  width: 0px;
  background: transparent;
  transition: width .5s ease, background-color .5s ease;
}
#sections li:hover:after {
  width: 100%;
  background: black;
}
```
